# This workflow will depliy the master branch to an existing EC2 instance

name: Master Branch Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Print directory
      run: |
        cd ..
        ls
        echo ${{ secrets.HOST }} > 'discordbot_v2.pem'
    - name: Connect to EC2 via SSH
      run: ssh -i "discordbot_v2.pem" ec2-user@ec2-18-144-30-103.us-west-1.compute.amazonaws.com
      
